const metroArray = [
    "Abrahamsberg",
    "Akalla",
    "Alby",
    "Alvik",
    "Aspudden",
    "Axelsberg",
    "Bagarmossen",
    "Bandhagen",
    "Bergshamra",
    "Björkhagen",
    "Blackeberg",
    "Blåsut",
    "Bredäng",
    "Brommaplan",
    "Danderyds sjukhus",
    "Duvbo",
    "Enskede gård",
    "Farsta",
    "Farsta strand",
    "Fittja",
    "Fridhemsplan",
    "Fruängen",
    "Gamla stan",
    "Globen",
    "Gubbängen",
    "Gullmarsplan",
    "Gärdet",
    "Hagsätra",
    "Hallonbergen",
    "Hallunda",
    "Hammarbyhöjden",
    "Hjulsta",
    "Hornstull",
    "Husby",
    "Huvudsta",
    "Hägerstensåsen",
    "Hässelby gård",
    "Hässelby strand",
    "Högdalen",
    "Hökarängen",
    "Hötorget",
    "Islandstorget",
    "Johannelund",
    "Karlaplan",
    "Kista",
    "Kristineberg",
    "Kungsträdgården",
    "Kymlinge",
    "Kärrtorp",
    "Liljeholmen",
    "Mariatorget",
    "Masmo",
    "Medborgarplatsen",
    "Midsommarkransen",
    "Mälarhöjden",
    "Mörby centrum",
    "Norsborg",
    "Näckrosen",
    "Odenplan",
    "Rinkeby",
    "Rissne",
    "Ropsten",
    "Råcksta",
    "Rådhuset",
    "Rådmansgatan",
    "Rågsved",
    "Sandsborg",
    "Sankt Eriksplan",
    "Skanstull",
    "Skarpnäck",
    "Skogskyrkogården",
    "Skärholmen",
    "Skärmarbrink",
    "Slussen",
    "Sockenplan",
    "Solna centrum",
    "Solna strand",
    "Stadion",
    "Stadshagen",
    "Stora mossen",
    "Stureby",
    "Sundbybergs centrum",
    "Svedmyra",
    "Sätra",
    "Tallkrogen",
    "T-Centralen",
    "Tekniska högskolan",
    "Telefonplan",
    "Tensta",
    "Thorildsplan",
    "Universitetet",
    "Vårberg",
    "Vårby gård",
    "Vällingby",
    "Västertorp",
    "Västra skogen",
    "Zinkensdamm",
    "Åkeshov",
    "Ängbyplan",
    "Örnsberg",
    "Östermalmstorg",
  ];
  
  export default metroArray;