const metroArray = [
    "Abrahamsberg",
    "Akalla",
    "Alby",
    "Alvik",
    "Aspudden",
    "Axelsberg",
    "Bagarmossen",
    "Bandhagen",
    "Bergshamra",
    "Björkhagen",
    "Blackeberg",
    "Blåsut",
    "Bredäng",
    "Brommaplan",
    "Danderyds sjukhus",
    "Duvbo",
    "Enskede gård",
    "Farsta",
    "Farsta strand",
    "Fittja",
    "Fridhemsplan",
    "Fruängen",
    "Gamla stan",
    "Globen (tidigare Isstadion och Slakthuset)",
    "Gubbängen",
    "Gullmarsplan (tidigare Johanneshov)",
    "Gärdet",
    "Hagsätra",
    "Hallonbergen",
    "Hallunda",
    "Hammarbyhöjden",
    "Hjulsta",
    "Hornstull",
    "Husby",
    "Huvudsta",
    "Hägerstensåsen",
    "Hässelby gård",
    "Hässelby strand",
    "Högdalen",
    "Hökarängen",
    "Hötorget (tidigare Kungsgatan)",
    "Islandstorget",
    "Johannelund",
    "Karlaplan",
    "Kista",
    "Kristineberg",
    "Kungsträdgården",
    "Kymlinge",
    "Kärrtorp",
    "Liljeholmen",
    "Mariatorget",
    "Masmo",
    "Medborgarplatsen",
    "Midsommarkransen",
    "Mälarhöjden",
    "Mörby centrum",
    "Norsborg",
    "Näckrosen",
    "Odenplan",
    "Rinkeby",
    "Rissne",
    "Ropsten",
    "Råcksta",
    "Rådhuset",
    "Rådmansgatan",
    "Rågsved",
    "Sandsborg",
    "Sankt Eriksplan",
    "Skanstull (tidigare Ringvägen)",
    "Skarpnäck",
    "Skogskyrkogården (tidigare Kyrkogården)",
    "Skärholmen",
    "Skärmarbrink (tidigare Hammarby)",
    "Slussen",
    "Sockenplan",
    "Solna centrum",
    "Solna strand (tidigare Vreten)",
    "Stadion",
    "Stadshagen",
    "Stora mossen",
    "Stureby",
    "Sundbybergs centrum",
    "Svedmyra",
    "Sätra",
    "Tallkrogen",
    "T-Centralen (tidigare Centralen)",
    "T-Centralen",
    "T-Centralen",
    "Tekniska högskolan",
    "Telefonplan",
    "Tensta",
    "Thorildsplan",
    "Universitetet",
    "Vårberg",
    "Vårby gård",
    "Vällingby",
    "Västertorp",
    "Västra skogen",
    "Zinkensdamm",
    "Åkeshov",
    "Ängbyplan (tidigare Färjestadsvägen)",
    "Örnsberg",
    "Östermalmstorg",
  ];
  
  export default metroArray;